# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

build:
  image: golang
  commands:
  - go get
  - go build
  - go test ./pkg/service

compose:
  redis:
    image: redis
    ports:
    - 6379
    links:
    - redis
